In [1]:
import numpy as np
a = np.array([[1, 2, 3],[3, 4, 6],[4,7,46]])
b = np.array ([[[2,5],[8,45]],[[22, 6],[43,9]]])
a


array([[ 1,  2,  3],
       [ 3,  4,  6],
       [ 4,  7, 46]])

In [2]:
b.ndim

3

In [3]:
print (a [ : , 0:2])

[[1 2]
 [3 4]
 [4 7]]


In [19]:
np.arange (2,20,2) ## give data from to to and last one is step up in sorted way

np.ones((3,5)) # gives materix for bracket dimesion and all vaules are 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(1,10,10) # equal number of parts from to to
np.eye(5)     # identity matrix


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(1)
np.random.rand(3,4) # give bracket dimension matrix with values are inbetween 0 to 1 

array([[0.6782333 , 0.37389587, 0.01554926, 0.98792372],
       [0.93323848, 0.28376425, 0.22263786, 0.95808414],
       [0.565596  , 0.18615104, 0.73394097, 0.48550143]])

In [15]:
np.random.randint(1,10,15) # gives values inbetween 1 to 10, last number is for number of values

array([3, 5, 8, 7, 5, 8, 2, 3, 5, 5, 1, 1, 8, 5, 4], dtype=int32)

In [16]:
np.random.randint(1,100,(10,10)) # here last value for dimension of matrix

array([[61, 32, 35, 29,  9, 65, 70, 91, 78, 67],
       [75, 37, 28, 35, 43, 19, 87, 80, 66,  1],
       [81, 31, 58, 16, 92, 81, 81, 49, 63, 98],
       [96, 26, 27, 73, 12, 45, 92, 24, 94, 68],
       [13, 55, 78, 18,  7,  4, 26, 27, 39, 65],
       [31, 97, 66, 48, 94, 11, 13, 55, 88, 69],
       [ 6, 99, 43, 13, 34, 99, 54, 17,  1, 82],
       [56, 28, 77, 12, 99, 80, 31, 17, 56, 95],
       [21, 87, 12, 29,  2,  3, 24, 95, 88,  3],
       [78, 94, 27, 12, 45, 52, 39, 42, 56, 82]], dtype=int32)

In [17]:
b=np.arange(50) # gives numbers in sorted way from 0 to 49
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
b=np.arange(50).reshape(5, 10) # to change above values to materix
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
#standard deviation ## variance # mean # median
import numpy as np
print (np.__version__, np.show_config) # Numpy Version and configration
a = [8, 12 , 16 , 24, 4]
print ("stand. deviation is", np.std(a))
print ("vari is", np.var(a))
m = np.mean(a)
print ("mean is",m)
med = np.median(a)
print ("meadian is",med)
#mod = np.(st.mode(a))
b = a - m
print ("Deviation from mean line", b)
Total = np.sum(b)
print ("Sum of deviation is", Total)
np.info




2.1.2 <function show at 0x000001D630B0F130>
stand. deviation is 6.881860213634101
vari is 47.36
mean is 12.8
meadian is 12.0
Deviation from mean line [-4.8 -0.8  3.2 11.2 -8.8]
Sum of deviation is -3.552713678800501e-15


<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

In [24]:
p = np.array ([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
p [:2,1:3]

np.eye(10) # identity matrix of 10
x = np.shape(p) # dim of matrix
print ("x is", x)
y = np.size(p)
print ("y is", y)




x is (3, 4)
y is 12


In [ ]:
## excercise 8

a = [9,12,17,20,13,10,6,5,3]
print ("median is" ,np.median(a))
print ("mean is" ,np.mean(a))


##excercise 9

salary = [25,40,35,50]
print ("std deviation is" ,np.std(salary))

salary1 = [25,25,25,40,40,35,50,50,50,50]
print ("std deviation is" ,np.std(salary1))


In [28]:
y=np.zeros(10)
y[4] = 1
y
x = np.arange(10,50)
x = x [::-1]  ## reverse
x




array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [29]:
z=np.arange(12).reshape(4,3)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.random.randint(0,8,(3,3))

array([[6, 1, 4],
       [1, 4, 2],
       [1, 2, 4]], dtype=int32)

In [33]:
d = [1,2,0,0,3]
d


[1, 2, 0, 0, 3]

In [36]:
d = [1,2,0,0,3]
print ("is it",d[d>0])

TypeError: '>' not supported between instances of 'list' and 'int'

In [37]:
x = np.ones((10,10))
x
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
m = np.random.randint(1,30,(5,6))
m


array([[ 1,  8,  3, 28, 18, 16],
       [28,  1, 25,  5, 22,  5],
       [ 1,  1,  9, 10, 18, 11],
       [ 6, 25, 23, 17, 26, 21],
       [15,  8, 16, 16,  7, 18]], dtype=int32)

In [39]:
np.mean(m)

np.float64(13.6)

In [12]:
import pandas as pd
dict = {'name':["Sunil", "pankaj", "sudhir", "Geeku"],
'degree': ["MBA", "BCA", "M.Tech", "MBA"],
'score':[90, 40, 80, 98]}
data = pd.DataFrame(dict)
print (data)

     name  degree  score
0   Sunil     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98


In [13]:
#data.loc['Sunil']
data.index = ['green','yellow','white','blue']
print (data)

          name  degree  score
green    Sunil     MBA     90
yellow  pankaj     BCA     40
white   sudhir  M.Tech     80
blue     Geeku     MBA     98
